"""add product sku

Revision ID: 394071832168
Revises: 
Create Date: 2026-09-11 14:50:41.340707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '394071832168'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Extend，先增加nullable的sku，因为数据库已经有数据
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'sku',
                sa.String(length=50),
                nullable=True
            )
        )

    # Backfill: 给历史数据生成临时但唯一的sku
    op.execute(
        """
        UPDATE product
        SET sku = 'LEGACY-' || id
        WHERE sku IS NULL
        """
    )

    # Conztract: 收紧Schema
    with op.batch_alter_table('product', schema=None) as batch_op:
        # Extend，先增加nullable的sku，因为数据库已经有数据
        batch_op.alter_column(
            'sku',
            existing_type=sa.String(length=50),
            nullable=False   
        )
        batch_op.create_unique_constraint(
            "uq_product_sku",
            ['sku']
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint("uq_product_sku", type_='unique')
        batch_op.drop_column('sku')

    # ### end Alembic commands ###
